# ||--Eureka--||
eureka.client.service-url.defaultZone=http://eureka-user:zvBGTYdMUJV7mpRs35YA@discovery-service:8761/eureka/
eureka.instance.prefer-ip-address=true

# ||--DB--||
spring.datasource.url=jdbc:mysql://mysql-db:3306/user_service_db
spring.datasource.username=ETA_DBUser
spring.datasource.password=${DB_PASSWORD}

# ||--RabbitMQ--||
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.username=rmuser
spring.rabbitmq.password=rmpassword

# ||--MinIO--||
minio.endpoint=http://minio:9000
minio.base.path=http://${SERVER_TAILSCALE_IP}:9000/user-service/